### ISSUE TITLE
Be a bit more complete on how to deploy the server

### ISSUE THREAD

**Issue by CalvoUTN** [Renegade-Master/zomboid-dedicated-server#10]
So, right now there are two tested images in DockerHub, yours and a Cyrale's fork which doesn't show the changes made to the Dockerfile. I say this because it that the author of that repo can be either too new to this to understand the importance of a public Dockerfile, or malicious intent.

This is important, because it's what got me here. I have a bit of experience selfhosting and know my way around Docker. But I feel this image needs a bit more documentation on how to fully deploy the server. For example, which ports need to be exposed? Both? Or just the one that the clients need to connect to? When do I change the configurations for my server, from the get go when deploying the container or afterwards?

I like the work you've done here and after I got it running as I want I'll try to PR what I feel is missing from the README, but I think it's important for someone with not much experience to have this info at hand so they don't feel too threatened.

**Comment by raykrueger** [comment]
I am also here because the other leading image is shady. This image is fantastic and I thank you for your work.

I have expert level knowledge on Docker and container services, so I got this running pretty easily. There were one or two parts that could use a deeper explanation. As @CalvoUTN said, a note on which ports are required would be helpful. Also, the difference between the two mount points and why they matter.

**Comment by Renegade-Master** [comment]
Thank you for the clarification on what documentation exactly could be improved. I should be able to take this and make the README a bit better. The only reason I had not acted on Calvo's suggestion was because I was honestly a bit unsure about what really should be clarified.
I will try to get to this over the weekend. It is a small change, but we're all devlopers here: we're always busy.

**Required/Not Required**
In general, if you want to just run the image without Docker-Compose, the arguments that are surrounded by square brackets (e.g. `[--env=ADMIN_PASSWORD=<value>]`) have sane defaults  automatically set by the startup process. You can leave those out if you like. Setting them allows the user to customise their instance with passwords, alternate ports, lists of mods, etc.

**Mount Points**
The mount points are for storing the game installation data, and the save/configuration data. I made them mount points as opposed to volumes so that the user can use third-party tools that interact with the save data or game files without having to first copy the data out of the container. It also allows the user to decide to use a different image if they don't like mine, and they can just take their saves/installation with them without any hassle.

**Ports**
The `QUERY_PORT` (16261) is used for finding the game. People wishing to join the server would use this port, paired with the public IP of the host to connect.
The `GAME_PORT` is the port that the game data is actually transferred over. The previous port is only for authentication. This port is for live game data.
The `RCON_PORT` was added recently. This port is for accepting RCON connections to control the server remotely using any RCON client. This can be very handy when running multiple servers at the same time, or if the user isn't particularly fond of CLI, they can use an RCON GUI to manage their server. This port is optional, and if you do not intend to use RCON, I would strongly suggest not exposing it, **_especially if you do not change the default password_**.

All of the aforementioned ports are configurable if the user wishes to use a port different to the defaults. I would recommend that they do in fact, for the same reason that you should change the default password on your home router: to make things slightly more awkward for bad actors who may wish to harm your experience.

**Comment by Renegade-Master** [comment]
@raykrueger 
That would be even better! If you can get something together, I'll review it, change anything (if necessary), and that would make the whole thing a lot easier.

I also want to add links to the alternative download locations if people would prefer to download from "not Dockerhub". I might throw that into your PR when it appears.

[RedHat Quay](https://quay.io/repository/renegade_master/zomboid-dedicated-server)
The above contains an automated `latest` tag.  I don't like `latest` tags, but people ask, so now it exists.

[GitHub Packages](https://github.com/users/Renegade-Master/packages/container/package/zomboid-dedicated-server)
Same as Dockerhub really, just without the rate limiting.

**Comment by raykrueger** [comment]
Sorry, I have to take that back. The GPL license makes it complicated for me to contribute. I'll stick to cheering you on from the sidelines :)

**Comment by Renegade-Master** [comment]
Hopefully that PR (#18) should help to address some of the questions raised here.

**Comment by Renegade-Master** [comment]
Please leave another comment if #18 did not actually explain enough things 🙂
