### ISSUE TITLE
docker-compose returns error

### ISSUE THREAD

**Issue by drophit** [Renegade-Master/zomboid-dedicated-server#56]
**Describe the bug**
When running docker-compose an error is returned - running docker-compose version 1.25.0, build unknown

**To Reproduce**
1. Cloned repository.
2. Built image with docker-compose up --detach
3. Started image using docker-compose up --detach
4. See attached error:

ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

Changing the version tag to "3 returns an error related to the yaml

**Comment by Renegade-Master** [comment]
Is there a particular reason that you are using such an old version of docker-compose?
The most recent version is [v2.15.1](https://github.com/docker/compose/releases).

It sounds like updating would resolve the issue in a better way than me downgrading the version for everyone else.

**Comment by Renegade-Master** [comment]
Have you tried updating your `docker-compose` client, yet, @drophit?

**Comment by Renegade-Master** [comment]
It's been quite a while. I am going to close this now.

Please re-open this if you are not happy with this resolution, @drophit

**Comment by gfxpixeldesigns** [comment]
Did you ever get this running on docker compose 1.25? I'm trying to set this up on a web server i lease monthly and I'm stuck with docker compose 1.23.2 because of cpanel limitations forcing python 2.7 and other older dependencies. So updating docker compose is not possible for me. Did you have any success? I tried ommitting the version tag as the compose docs state under versioning but i guess there is more to it than that.
